### ISSUE TITLE
Myshrall-Shaylyn-3-Kraken-Good-Accessibility 

### ISSUE THREAD

**Issue by ShaylynHM** [ShaylynHM/kraken-good-accessibility#1]
@thatkidmadrid
Almost there! Maybe you can help me find what is making this different
<img width="1014" alt="Screen Shot 2021-10-15 at 4 09 12 PM" src="https://user-images.githubusercontent.com/77545465/137547667-9abe94b9-1914-4db6-9669-69c134f571e6.png">
?

**Comment by thatkidmadrid** [comment]
it's not really clear what's causing this difference, but on `line 69`  to `line 115` you can throw that into the `div` with the class `main` that you set up. that might push some things into place an get that difference less than 12

the icons I provided aren't the same as the original so you can still expect that to be a bit off, but the positioning of the text might be off due to the structure.
